AllBlocksOneWorld: false          ##set this value to false if you want to only spawn regular blocks in the normal world. (Useful when wanting a Nether or End Skygrid world)

## 16, 32, 48, 64, 80, 96, 112, 128, 144, 160, 176, 192, 208, 224, 240, 256 (these are recommended world heights)
## These are the numbers used to generate the blocks in the Grid Randomly
## Each number must be less than the next and not more than 9999. You could in theory Max your mythic probability by doing:
## MythicBlockProbability: 9996
## UniqueBlockProbability: 9997
## RareBlockProbability: 9998
## UncommonBlockProbability: 9999
## I have java generate a random number between 0 and 10000(exclusive). So, really what these numbers are doing
## is telling the chunk generator to generate a random block from a group of blocks(ie mythic) if the random number is less than
## the figure you set here. So, if the random number is 181 it will pick a random block from the rare block set and not the unique block set
## (under the default config) because 181 is not less than 181. There is one more group of blocks that is generated that is not listed here.
## these blocks get the remainder of the 10000 above the number set by the uncommon block group. So with the current default configuration,
## a random number from 4001 to 9999 will spawn an abundant group block.

ReplaceAirWithGlass: false
World_Height: 128                ##A higher number here will increase the stress on your computer rendering blocks.
Mythic_Block_Probability: 4
Unique_Block_Probability: 181
Rare_Block_Probability: 1801
Uncommon_Block_Probability: 4001
##If AllBlocksOneWorld is true, edit these blockgroup values. If its false scroll down to NormalConfig.
##These are the block Id's in each of the 5 groups. You must have at least 1 Id in each group.
##Make sure there is only one space in between each Id.

BlockGroups:
  Mythic: 'SPONGE PURPUR_BLOCK END_STONE_BRICKS CAULDRON CAKE TNT PISTON REDSTONE_BLOCK BLUE_ICE SEA_LANTERN LILY_PAD EMERALD_ORE LAPIS_ORE DIAMOND_ORE BUDDING_AMETHYST BOOKSHELF HAY_BLOCK SPAWNER PUMPKIN MOSS_BLOCK MELON MYCELIUM'
  Unique: 'END_STONE PRISMARINE GOLD_ORE REDSTONE_ORE COBWEB WHITE_WOOL BRICKS OBSIDIAN ICE SNOW_BLOCK WHITE_TERRACOTTA LAVA MAGMA_BLOCK NETHER_GOLD_ORE NETHER_QUARTZ_ORE ANCIENT_DEBRIS GLOWSTONE NETHER_BRICKS CRYING_OBSIDIAN'
  Rare: 'CRIMSON_NYLIUM WARPED_NYLIUM NETHERRACK SOUL_SAND SOUL_SOIL BASALT BLACKSTONE LIGHT_GRAY_CONCRETE CALCITE TUFF DRIPSTONE_BLOCK IRON_ORE COPPER_ORE MOSSY_COBBLESTONE CLAY WATER CHEST'
  Uncommon: 'GLASS DEEPSLATE ANDESITE RED_SAND GRAVEL COAL_ORE SANDSTONE'
  Abundant: 'STONE GRANITE DIORITE GRASS_BLOCK DIRT SAND OAK_LOG'

##The plugin generates a random number between 0 and 99 here. If you set Spawn_Prob_Mythic to 10 and Spawn_Prob_Rare to 20 for instance,
##the plugin will select from the mythic list on random numbers 0 - 9, from the Rare list on random numbers 10 - 19, and the Normal list from 20 to 99.
Spawn_Prob_Mythic: 10
Spawn_Prob_Rare: 30

##If AllBlocksOneWorld is true these values will modify determine the chance for nether or end chest loot tables to be used instead of normal loot tables
##These values use the same logic as the spawner picking above
##If AllBlocksOneWorld is false these values are ignored
Chest_Prob_End: 5
Chest_Prob_Nether: 15

## If AllBlocksOneWorld at the very top of this config is false, you'll want to edit these values to change what blocks can spawn in a normal world.
## The block probability values from above will still apply to these blocks. So will the chest probability values

NormalConfig:
  BlockGroups:
    Mythic: 'SPONGE CAULDRON CAKE TNT PISTON REDSTONE_BLOCK BLUE_ICE SEA_LANTERN LILY_PAD EMERALD_ORE LAPIS_ORE DIAMOND_ORE BUDDING_AMETHYST BOOKSHELF HAY_BLOCK PUMPKIN MOSS_BLOCK MELON MYCELIUM'
    Unique: 'PRISMARINE GOLD_ORE REDSTONE_ORE COBWEB WHITE_WOOL BRICKS OBSIDIAN ICE SNOW_BLOCK WHITE_TERRACOTTA LAVA SPAWNER'
    Rare: 'LIGHT_GRAY_CONCRETE CALCITE TUFF DRIPSTONE_BLOCK IRON_ORE COPPER_ORE MOSSY_COBBLESTONE CLAY WATER CHEST'
    Uncommon: 'GLASS DEEPSLATE ANDESITE RED_SAND GRAVEL COAL_ORE SANDSTONE'
    Abundant: 'STONE GRANITE DIORITE GRASS_BLOCK DIRT SAND OAK_LOG'
  SpawnerOptions:
    Mythic: 'ELDER_GUARDIAN ZOMBIE_HORSE EVOKER ILLUSIONER GUARDIAN VILLAGER'
    Rare: 'ZOMBIE_VILLAGER VINDICATOR SILVERFISH WITCH RAVAGER'
    Abundant: 'STRAY HUSK CREEPER SKELETON SPIDER ZOMBIE ENDERMAN CAVE_SPIDER DROWNED PILLAGER'

## Note OAK_LOG will be replaced by the nether appropriate logs during world gen in the nether
NetherConfig:
  Nether_World_Height: 128
  NetherBlocks:
    Rare: 'MAGMA_BLOCK NETHER_GOLD_ORE NETHER_QUARTZ_ORE ANCIENT_DEBRIS GLOWSTONE NETHER_BRICKS CRYING_OBSIDIAN CHEST SPAWNER'
    Normal: 'CRIMSON_NYLIUM WARPED_NYLIUM NETHERRACK SOUL_SAND SOUL_SOIL BASALT BLACKSTONE OAK_LOG'
  SpawnerOptions:
    Mythic: 'WITHER_SKELETON PIGLIN_BRUTE'
    Rare: 'GHAST ZOMBIFIED_PIGLIN BLAZE ENDERMAN'
    Abundant: 'PIGLIN HOGLIN ZOGLIN'

EndConfig:
  End_World_Height: 128
  EndBlocks:
    Rare: 'PURPUR_BLOCK CHEST SPAWNER'
    Normal: 'END_STONE OBSIDIAN'
  SpawnerOptions:
    Mythic: 'SHULKER'
    Rare: 'ENDERMAN'
    Abundant: 'ENDERMAN'